[book]
title = "Rust By Practice"
description = "Learn Rust with Example, Exercise and real Practice, written with ❤️ by https://course.rs team"
authors = ["sunface, https://im.dev"]
language = "en"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true
level = 1

[output.html]
git-repository-url = "https://github.com/sunface/rust-by-practice"
edit-url-template = "https://github.com/sunface/rust-by-practice/edit/master/en/{path}"

[rust]
edition = "2021"