[book]
title = "Rust By Practice( Rust 练习实践 )"
description = "Learning Rust By Practice, narrowing the gap between beginner and skilled-dev with challenging examples, exercises and projects."
authors = ["sunface, https://im.dev"]
language = "en"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true
level = 1

[output.html]
additional-css = ["theme/style1.css"]
additional-js = ["assets/custom3.js", "assets/lang1.js","assets/shortcut-key.js"]
git-repository-url = "https://github.com/sunface/rust-by-practice"
edit-url-template = "https://github.com/sunface/rust-by-practice/edit/master/zh-CN/{path}"

[rust]
edition = "2021"
